package com.example.feedforward;

public enum Categories {

    AVAILABLE_AREA, BIRTHDAY, BLACK_LIST, BULK, BUY_CHARGE, BUY_PACKAGE_CALL, BUY_PACKAGE_CUSTOM,
    BUY_PACKAGE_INTERNET, BUY_PACKAGE_MESSAGE, CALL_RESTRICTION, CDR, CLUB, CREDIT_TRANSFER,
    FAQ, FEEDBACK, INCREASE_CREDIT, INSTALLMENT, MCA, MCI_OFFICE, MENU, MY_BILL, MY_CHARGE, MY_PACKAGE, PAY_BILL, RBT, REVIEW, ROAMING, SERVICES, SHOP, SIMCART_MANAGMENT, SIMPLE_MODE, SPEED_TEST,
    SUPPORT, SWITCH_TO_POST, TRIFF, VAS, VOICE_MAIL, WALLET, GREETING

}
